name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    # this event is submited via github.com/bots-house/github-actions-upstream-watch
    types: upstream_commit
  schedule:
    - cron: '0 2 * * 0'

             
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps: 
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout upstream repo 
        uses: actions/checkout@v2
        with:
          repository: nxtrace/NTrace-core
          path: upstream
          submodules: recursive  
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Get Latest Tag Of Upstream Source Code
        id: download
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/nxtrace/NTrace-core/releases" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          echo ::set-output name=latest_tag::${VERSION:1}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nxtrace:latest, ${{ secrets.DOCKERHUB_USERNAME }}/nxtrace:${{ steps.download.outputs.latest_tag }}
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/nxtrace:latest
          
